// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcrypto

import (
	"context"

	"github.com/alwitt/cgoutils/crypto"
	mock "github.com/stretchr/testify/mock"
)

// NewAEAD creates a new instance of AEAD. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAEAD(t interface {
	mock.TestingT
	Cleanup(func())
}) *AEAD {
	mock := &AEAD{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AEAD is an autogenerated mock type for the AEAD type
type AEAD struct {
	mock.Mock
}

type AEAD_Expecter struct {
	mock *mock.Mock
}

func (_m *AEAD) EXPECT() *AEAD_Expecter {
	return &AEAD_Expecter{mock: &_m.Mock}
}

// ExpectedCipherLen provides a mock function for the type AEAD
func (_mock *AEAD) ExpectedCipherLen(plainTextLen int64) int64 {
	ret := _mock.Called(plainTextLen)

	if len(ret) == 0 {
		panic("no return value specified for ExpectedCipherLen")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(int64) int64); ok {
		r0 = returnFunc(plainTextLen)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// AEAD_ExpectedCipherLen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpectedCipherLen'
type AEAD_ExpectedCipherLen_Call struct {
	*mock.Call
}

// ExpectedCipherLen is a helper method to define mock.On call
//   - plainTextLen int64
func (_e *AEAD_Expecter) ExpectedCipherLen(plainTextLen interface{}) *AEAD_ExpectedCipherLen_Call {
	return &AEAD_ExpectedCipherLen_Call{Call: _e.mock.On("ExpectedCipherLen", plainTextLen)}
}

func (_c *AEAD_ExpectedCipherLen_Call) Run(run func(plainTextLen int64)) *AEAD_ExpectedCipherLen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AEAD_ExpectedCipherLen_Call) Return(n int64) *AEAD_ExpectedCipherLen_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *AEAD_ExpectedCipherLen_Call) RunAndReturn(run func(plainTextLen int64) int64) *AEAD_ExpectedCipherLen_Call {
	_c.Call.Return(run)
	return _c
}

// ExpectedKeyLen provides a mock function for the type AEAD
func (_mock *AEAD) ExpectedKeyLen() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExpectedKeyLen")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// AEAD_ExpectedKeyLen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpectedKeyLen'
type AEAD_ExpectedKeyLen_Call struct {
	*mock.Call
}

// ExpectedKeyLen is a helper method to define mock.On call
func (_e *AEAD_Expecter) ExpectedKeyLen() *AEAD_ExpectedKeyLen_Call {
	return &AEAD_ExpectedKeyLen_Call{Call: _e.mock.On("ExpectedKeyLen")}
}

func (_c *AEAD_ExpectedKeyLen_Call) Run(run func()) *AEAD_ExpectedKeyLen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AEAD_ExpectedKeyLen_Call) Return(n int) *AEAD_ExpectedKeyLen_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *AEAD_ExpectedKeyLen_Call) RunAndReturn(run func() int) *AEAD_ExpectedKeyLen_Call {
	_c.Call.Return(run)
	return _c
}

// ExpectedNonceLen provides a mock function for the type AEAD
func (_mock *AEAD) ExpectedNonceLen() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExpectedNonceLen")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// AEAD_ExpectedNonceLen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpectedNonceLen'
type AEAD_ExpectedNonceLen_Call struct {
	*mock.Call
}

// ExpectedNonceLen is a helper method to define mock.On call
func (_e *AEAD_Expecter) ExpectedNonceLen() *AEAD_ExpectedNonceLen_Call {
	return &AEAD_ExpectedNonceLen_Call{Call: _e.mock.On("ExpectedNonceLen")}
}

func (_c *AEAD_ExpectedNonceLen_Call) Run(run func()) *AEAD_ExpectedNonceLen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AEAD_ExpectedNonceLen_Call) Return(n int) *AEAD_ExpectedNonceLen_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *AEAD_ExpectedNonceLen_Call) RunAndReturn(run func() int) *AEAD_ExpectedNonceLen_Call {
	_c.Call.Return(run)
	return _c
}

// ExpectedPlainTextLen provides a mock function for the type AEAD
func (_mock *AEAD) ExpectedPlainTextLen(cipherLen int64) int64 {
	ret := _mock.Called(cipherLen)

	if len(ret) == 0 {
		panic("no return value specified for ExpectedPlainTextLen")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(int64) int64); ok {
		r0 = returnFunc(cipherLen)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// AEAD_ExpectedPlainTextLen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpectedPlainTextLen'
type AEAD_ExpectedPlainTextLen_Call struct {
	*mock.Call
}

// ExpectedPlainTextLen is a helper method to define mock.On call
//   - cipherLen int64
func (_e *AEAD_Expecter) ExpectedPlainTextLen(cipherLen interface{}) *AEAD_ExpectedPlainTextLen_Call {
	return &AEAD_ExpectedPlainTextLen_Call{Call: _e.mock.On("ExpectedPlainTextLen", cipherLen)}
}

func (_c *AEAD_ExpectedPlainTextLen_Call) Run(run func(cipherLen int64)) *AEAD_ExpectedPlainTextLen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AEAD_ExpectedPlainTextLen_Call) Return(n int64) *AEAD_ExpectedPlainTextLen_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *AEAD_ExpectedPlainTextLen_Call) RunAndReturn(run func(cipherLen int64) int64) *AEAD_ExpectedPlainTextLen_Call {
	_c.Call.Return(run)
	return _c
}

// Nonce provides a mock function for the type AEAD
func (_mock *AEAD) Nonce() crypto.SecureCSlice {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Nonce")
	}

	var r0 crypto.SecureCSlice
	if returnFunc, ok := ret.Get(0).(func() crypto.SecureCSlice); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.SecureCSlice)
		}
	}
	return r0
}

// AEAD_Nonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nonce'
type AEAD_Nonce_Call struct {
	*mock.Call
}

// Nonce is a helper method to define mock.On call
func (_e *AEAD_Expecter) Nonce() *AEAD_Nonce_Call {
	return &AEAD_Nonce_Call{Call: _e.mock.On("Nonce")}
}

func (_c *AEAD_Nonce_Call) Run(run func()) *AEAD_Nonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AEAD_Nonce_Call) Return(secureCSlice crypto.SecureCSlice) *AEAD_Nonce_Call {
	_c.Call.Return(secureCSlice)
	return _c
}

func (_c *AEAD_Nonce_Call) RunAndReturn(run func() crypto.SecureCSlice) *AEAD_Nonce_Call {
	_c.Call.Return(run)
	return _c
}

// ResetNonce provides a mock function for the type AEAD
func (_mock *AEAD) ResetNonce(ctxt context.Context) error {
	ret := _mock.Called(ctxt)

	if len(ret) == 0 {
		panic("no return value specified for ResetNonce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctxt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AEAD_ResetNonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetNonce'
type AEAD_ResetNonce_Call struct {
	*mock.Call
}

// ResetNonce is a helper method to define mock.On call
//   - ctxt context.Context
func (_e *AEAD_Expecter) ResetNonce(ctxt interface{}) *AEAD_ResetNonce_Call {
	return &AEAD_ResetNonce_Call{Call: _e.mock.On("ResetNonce", ctxt)}
}

func (_c *AEAD_ResetNonce_Call) Run(run func(ctxt context.Context)) *AEAD_ResetNonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AEAD_ResetNonce_Call) Return(err error) *AEAD_ResetNonce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AEAD_ResetNonce_Call) RunAndReturn(run func(ctxt context.Context) error) *AEAD_ResetNonce_Call {
	_c.Call.Return(run)
	return _c
}

// Seal provides a mock function for the type AEAD
func (_mock *AEAD) Seal(ctxt context.Context, msgIndex int64, plainText []byte, additional []byte, cipherText []byte) error {
	ret := _mock.Called(ctxt, msgIndex, plainText, additional, cipherText)

	if len(ret) == 0 {
		panic("no return value specified for Seal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []byte, []byte, []byte) error); ok {
		r0 = returnFunc(ctxt, msgIndex, plainText, additional, cipherText)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AEAD_Seal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seal'
type AEAD_Seal_Call struct {
	*mock.Call
}

// Seal is a helper method to define mock.On call
//   - ctxt context.Context
//   - msgIndex int64
//   - plainText []byte
//   - additional []byte
//   - cipherText []byte
func (_e *AEAD_Expecter) Seal(ctxt interface{}, msgIndex interface{}, plainText interface{}, additional interface{}, cipherText interface{}) *AEAD_Seal_Call {
	return &AEAD_Seal_Call{Call: _e.mock.On("Seal", ctxt, msgIndex, plainText, additional, cipherText)}
}

func (_c *AEAD_Seal_Call) Run(run func(ctxt context.Context, msgIndex int64, plainText []byte, additional []byte, cipherText []byte)) *AEAD_Seal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AEAD_Seal_Call) Return(err error) *AEAD_Seal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AEAD_Seal_Call) RunAndReturn(run func(ctxt context.Context, msgIndex int64, plainText []byte, additional []byte, cipherText []byte) error) *AEAD_Seal_Call {
	_c.Call.Return(run)
	return _c
}

// SetKey provides a mock function for the type AEAD
func (_mock *AEAD) SetKey(key crypto.SecureCSlice) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for SetKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(crypto.SecureCSlice) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AEAD_SetKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetKey'
type AEAD_SetKey_Call struct {
	*mock.Call
}

// SetKey is a helper method to define mock.On call
//   - key crypto.SecureCSlice
func (_e *AEAD_Expecter) SetKey(key interface{}) *AEAD_SetKey_Call {
	return &AEAD_SetKey_Call{Call: _e.mock.On("SetKey", key)}
}

func (_c *AEAD_SetKey_Call) Run(run func(key crypto.SecureCSlice)) *AEAD_SetKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 crypto.SecureCSlice
		if args[0] != nil {
			arg0 = args[0].(crypto.SecureCSlice)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AEAD_SetKey_Call) Return(err error) *AEAD_SetKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AEAD_SetKey_Call) RunAndReturn(run func(key crypto.SecureCSlice) error) *AEAD_SetKey_Call {
	_c.Call.Return(run)
	return _c
}

// SetNonce provides a mock function for the type AEAD
func (_mock *AEAD) SetNonce(nonce crypto.SecureCSlice) error {
	ret := _mock.Called(nonce)

	if len(ret) == 0 {
		panic("no return value specified for SetNonce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(crypto.SecureCSlice) error); ok {
		r0 = returnFunc(nonce)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AEAD_SetNonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNonce'
type AEAD_SetNonce_Call struct {
	*mock.Call
}

// SetNonce is a helper method to define mock.On call
//   - nonce crypto.SecureCSlice
func (_e *AEAD_Expecter) SetNonce(nonce interface{}) *AEAD_SetNonce_Call {
	return &AEAD_SetNonce_Call{Call: _e.mock.On("SetNonce", nonce)}
}

func (_c *AEAD_SetNonce_Call) Run(run func(nonce crypto.SecureCSlice)) *AEAD_SetNonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 crypto.SecureCSlice
		if args[0] != nil {
			arg0 = args[0].(crypto.SecureCSlice)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AEAD_SetNonce_Call) Return(err error) *AEAD_SetNonce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AEAD_SetNonce_Call) RunAndReturn(run func(nonce crypto.SecureCSlice) error) *AEAD_SetNonce_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type AEAD
func (_mock *AEAD) Type() crypto.AEADTypeEnum {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 crypto.AEADTypeEnum
	if returnFunc, ok := ret.Get(0).(func() crypto.AEADTypeEnum); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(crypto.AEADTypeEnum)
	}
	return r0
}

// AEAD_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type AEAD_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *AEAD_Expecter) Type() *AEAD_Type_Call {
	return &AEAD_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *AEAD_Type_Call) Run(run func()) *AEAD_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AEAD_Type_Call) Return(aEADTypeEnum crypto.AEADTypeEnum) *AEAD_Type_Call {
	_c.Call.Return(aEADTypeEnum)
	return _c
}

func (_c *AEAD_Type_Call) RunAndReturn(run func() crypto.AEADTypeEnum) *AEAD_Type_Call {
	_c.Call.Return(run)
	return _c
}

// Unseal provides a mock function for the type AEAD
func (_mock *AEAD) Unseal(ctxt context.Context, msgIndex int64, cipherText []byte, additional []byte, plainText []byte) error {
	ret := _mock.Called(ctxt, msgIndex, cipherText, additional, plainText)

	if len(ret) == 0 {
		panic("no return value specified for Unseal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []byte, []byte, []byte) error); ok {
		r0 = returnFunc(ctxt, msgIndex, cipherText, additional, plainText)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AEAD_Unseal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unseal'
type AEAD_Unseal_Call struct {
	*mock.Call
}

// Unseal is a helper method to define mock.On call
//   - ctxt context.Context
//   - msgIndex int64
//   - cipherText []byte
//   - additional []byte
//   - plainText []byte
func (_e *AEAD_Expecter) Unseal(ctxt interface{}, msgIndex interface{}, cipherText interface{}, additional interface{}, plainText interface{}) *AEAD_Unseal_Call {
	return &AEAD_Unseal_Call{Call: _e.mock.On("Unseal", ctxt, msgIndex, cipherText, additional, plainText)}
}

func (_c *AEAD_Unseal_Call) Run(run func(ctxt context.Context, msgIndex int64, cipherText []byte, additional []byte, plainText []byte)) *AEAD_Unseal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AEAD_Unseal_Call) Return(err error) *AEAD_Unseal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AEAD_Unseal_Call) RunAndReturn(run func(ctxt context.Context, msgIndex int64, cipherText []byte, additional []byte, plainText []byte) error) *AEAD_Unseal_Call {
	_c.Call.Return(run)
	return _c
}
