// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcrypto

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewCFSSLClient creates a new instance of CFSSLClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCFSSLClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CFSSLClient {
	mock := &CFSSLClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CFSSLClient is an autogenerated mock type for the CFSSLClient type
type CFSSLClient struct {
	mock.Mock
}

type CFSSLClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CFSSLClient) EXPECT() *CFSSLClient_Expecter {
	return &CFSSLClient_Expecter{mock: &_m.Mock}
}

// SignCSR provides a mock function for the type CFSSLClient
func (_mock *CFSSLClient) SignCSR(ctxt context.Context, csrPayload string, certProfile string) (string, error) {
	ret := _mock.Called(ctxt, csrPayload, certProfile)

	if len(ret) == 0 {
		panic("no return value specified for SignCSR")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctxt, csrPayload, certProfile)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctxt, csrPayload, certProfile)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctxt, csrPayload, certProfile)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CFSSLClient_SignCSR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignCSR'
type CFSSLClient_SignCSR_Call struct {
	*mock.Call
}

// SignCSR is a helper method to define mock.On call
//   - ctxt context.Context
//   - csrPayload string
//   - certProfile string
func (_e *CFSSLClient_Expecter) SignCSR(ctxt interface{}, csrPayload interface{}, certProfile interface{}) *CFSSLClient_SignCSR_Call {
	return &CFSSLClient_SignCSR_Call{Call: _e.mock.On("SignCSR", ctxt, csrPayload, certProfile)}
}

func (_c *CFSSLClient_SignCSR_Call) Run(run func(ctxt context.Context, csrPayload string, certProfile string)) *CFSSLClient_SignCSR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CFSSLClient_SignCSR_Call) Return(s string, err error) *CFSSLClient_SignCSR_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *CFSSLClient_SignCSR_Call) RunAndReturn(run func(ctxt context.Context, csrPayload string, certProfile string) (string, error)) *CFSSLClient_SignCSR_Call {
	_c.Call.Return(run)
	return _c
}
