// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcrypto

import (
	"context"
	"crypto/ed25519"
	"crypto/rsa"
	"crypto/x509"
	"io"

	"github.com/alwitt/cgoutils/crypto"
	mock "github.com/stretchr/testify/mock"
)

// NewEngine creates a new instance of Engine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *Engine {
	mock := &Engine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Engine is an autogenerated mock type for the Engine type
type Engine struct {
	mock.Mock
}

type Engine_Expecter struct {
	mock *mock.Mock
}

func (_m *Engine) EXPECT() *Engine_Expecter {
	return &Engine_Expecter{mock: &_m.Mock}
}

// AllocateSecureCSlice provides a mock function for the type Engine
func (_mock *Engine) AllocateSecureCSlice(length int) (crypto.SecureCSlice, error) {
	ret := _mock.Called(length)

	if len(ret) == 0 {
		panic("no return value specified for AllocateSecureCSlice")
	}

	var r0 crypto.SecureCSlice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (crypto.SecureCSlice, error)); ok {
		return returnFunc(length)
	}
	if returnFunc, ok := ret.Get(0).(func(int) crypto.SecureCSlice); ok {
		r0 = returnFunc(length)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.SecureCSlice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(length)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_AllocateSecureCSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllocateSecureCSlice'
type Engine_AllocateSecureCSlice_Call struct {
	*mock.Call
}

// AllocateSecureCSlice is a helper method to define mock.On call
//   - length int
func (_e *Engine_Expecter) AllocateSecureCSlice(length interface{}) *Engine_AllocateSecureCSlice_Call {
	return &Engine_AllocateSecureCSlice_Call{Call: _e.mock.On("AllocateSecureCSlice", length)}
}

func (_c *Engine_AllocateSecureCSlice_Call) Run(run func(length int)) *Engine_AllocateSecureCSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Engine_AllocateSecureCSlice_Call) Return(secureCSlice crypto.SecureCSlice, err error) *Engine_AllocateSecureCSlice_Call {
	_c.Call.Return(secureCSlice, err)
	return _c
}

func (_c *Engine_AllocateSecureCSlice_Call) RunAndReturn(run func(length int) (crypto.SecureCSlice, error)) *Engine_AllocateSecureCSlice_Call {
	_c.Call.Return(run)
	return _c
}

// ComputeClientECDHSessionKeys provides a mock function for the type Engine
func (_mock *Engine) ComputeClientECDHSessionKeys(ctxt context.Context, clientKeys crypto.ECDHKeyPair, serverPublic crypto.SecureCSlice) (crypto.ECDHSessionKeys, error) {
	ret := _mock.Called(ctxt, clientKeys, serverPublic)

	if len(ret) == 0 {
		panic("no return value specified for ComputeClientECDHSessionKeys")
	}

	var r0 crypto.ECDHSessionKeys
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.ECDHKeyPair, crypto.SecureCSlice) (crypto.ECDHSessionKeys, error)); ok {
		return returnFunc(ctxt, clientKeys, serverPublic)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.ECDHKeyPair, crypto.SecureCSlice) crypto.ECDHSessionKeys); ok {
		r0 = returnFunc(ctxt, clientKeys, serverPublic)
	} else {
		r0 = ret.Get(0).(crypto.ECDHSessionKeys)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crypto.ECDHKeyPair, crypto.SecureCSlice) error); ok {
		r1 = returnFunc(ctxt, clientKeys, serverPublic)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_ComputeClientECDHSessionKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComputeClientECDHSessionKeys'
type Engine_ComputeClientECDHSessionKeys_Call struct {
	*mock.Call
}

// ComputeClientECDHSessionKeys is a helper method to define mock.On call
//   - ctxt context.Context
//   - clientKeys crypto.ECDHKeyPair
//   - serverPublic crypto.SecureCSlice
func (_e *Engine_Expecter) ComputeClientECDHSessionKeys(ctxt interface{}, clientKeys interface{}, serverPublic interface{}) *Engine_ComputeClientECDHSessionKeys_Call {
	return &Engine_ComputeClientECDHSessionKeys_Call{Call: _e.mock.On("ComputeClientECDHSessionKeys", ctxt, clientKeys, serverPublic)}
}

func (_c *Engine_ComputeClientECDHSessionKeys_Call) Run(run func(ctxt context.Context, clientKeys crypto.ECDHKeyPair, serverPublic crypto.SecureCSlice)) *Engine_ComputeClientECDHSessionKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crypto.ECDHKeyPair
		if args[1] != nil {
			arg1 = args[1].(crypto.ECDHKeyPair)
		}
		var arg2 crypto.SecureCSlice
		if args[2] != nil {
			arg2 = args[2].(crypto.SecureCSlice)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Engine_ComputeClientECDHSessionKeys_Call) Return(eCDHSessionKeys crypto.ECDHSessionKeys, err error) *Engine_ComputeClientECDHSessionKeys_Call {
	_c.Call.Return(eCDHSessionKeys, err)
	return _c
}

func (_c *Engine_ComputeClientECDHSessionKeys_Call) RunAndReturn(run func(ctxt context.Context, clientKeys crypto.ECDHKeyPair, serverPublic crypto.SecureCSlice) (crypto.ECDHSessionKeys, error)) *Engine_ComputeClientECDHSessionKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ComputeServerECDHSessionKeys provides a mock function for the type Engine
func (_mock *Engine) ComputeServerECDHSessionKeys(ctxt context.Context, serverKeys crypto.ECDHKeyPair, clientPublic crypto.SecureCSlice) (crypto.ECDHSessionKeys, error) {
	ret := _mock.Called(ctxt, serverKeys, clientPublic)

	if len(ret) == 0 {
		panic("no return value specified for ComputeServerECDHSessionKeys")
	}

	var r0 crypto.ECDHSessionKeys
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.ECDHKeyPair, crypto.SecureCSlice) (crypto.ECDHSessionKeys, error)); ok {
		return returnFunc(ctxt, serverKeys, clientPublic)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.ECDHKeyPair, crypto.SecureCSlice) crypto.ECDHSessionKeys); ok {
		r0 = returnFunc(ctxt, serverKeys, clientPublic)
	} else {
		r0 = ret.Get(0).(crypto.ECDHSessionKeys)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crypto.ECDHKeyPair, crypto.SecureCSlice) error); ok {
		r1 = returnFunc(ctxt, serverKeys, clientPublic)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_ComputeServerECDHSessionKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComputeServerECDHSessionKeys'
type Engine_ComputeServerECDHSessionKeys_Call struct {
	*mock.Call
}

// ComputeServerECDHSessionKeys is a helper method to define mock.On call
//   - ctxt context.Context
//   - serverKeys crypto.ECDHKeyPair
//   - clientPublic crypto.SecureCSlice
func (_e *Engine_Expecter) ComputeServerECDHSessionKeys(ctxt interface{}, serverKeys interface{}, clientPublic interface{}) *Engine_ComputeServerECDHSessionKeys_Call {
	return &Engine_ComputeServerECDHSessionKeys_Call{Call: _e.mock.On("ComputeServerECDHSessionKeys", ctxt, serverKeys, clientPublic)}
}

func (_c *Engine_ComputeServerECDHSessionKeys_Call) Run(run func(ctxt context.Context, serverKeys crypto.ECDHKeyPair, clientPublic crypto.SecureCSlice)) *Engine_ComputeServerECDHSessionKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crypto.ECDHKeyPair
		if args[1] != nil {
			arg1 = args[1].(crypto.ECDHKeyPair)
		}
		var arg2 crypto.SecureCSlice
		if args[2] != nil {
			arg2 = args[2].(crypto.SecureCSlice)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Engine_ComputeServerECDHSessionKeys_Call) Return(eCDHSessionKeys crypto.ECDHSessionKeys, err error) *Engine_ComputeServerECDHSessionKeys_Call {
	_c.Call.Return(eCDHSessionKeys, err)
	return _c
}

func (_c *Engine_ComputeServerECDHSessionKeys_Call) RunAndReturn(run func(ctxt context.Context, serverKeys crypto.ECDHKeyPair, clientPublic crypto.SecureCSlice) (crypto.ECDHSessionKeys, error)) *Engine_ComputeServerECDHSessionKeys_Call {
	_c.Call.Return(run)
	return _c
}

// CreateED25519CSR provides a mock function for the type Engine
func (_mock *Engine) CreateED25519CSR(ctxt context.Context, csrParams crypto.CertSigningRequestParams) (ed25519.PrivateKey, []byte, error) {
	ret := _mock.Called(ctxt, csrParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateED25519CSR")
	}

	var r0 ed25519.PrivateKey
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.CertSigningRequestParams) (ed25519.PrivateKey, []byte, error)); ok {
		return returnFunc(ctxt, csrParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.CertSigningRequestParams) ed25519.PrivateKey); ok {
		r0 = returnFunc(ctxt, csrParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ed25519.PrivateKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crypto.CertSigningRequestParams) []byte); ok {
		r1 = returnFunc(ctxt, csrParams)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, crypto.CertSigningRequestParams) error); ok {
		r2 = returnFunc(ctxt, csrParams)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Engine_CreateED25519CSR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateED25519CSR'
type Engine_CreateED25519CSR_Call struct {
	*mock.Call
}

// CreateED25519CSR is a helper method to define mock.On call
//   - ctxt context.Context
//   - csrParams crypto.CertSigningRequestParams
func (_e *Engine_Expecter) CreateED25519CSR(ctxt interface{}, csrParams interface{}) *Engine_CreateED25519CSR_Call {
	return &Engine_CreateED25519CSR_Call{Call: _e.mock.On("CreateED25519CSR", ctxt, csrParams)}
}

func (_c *Engine_CreateED25519CSR_Call) Run(run func(ctxt context.Context, csrParams crypto.CertSigningRequestParams)) *Engine_CreateED25519CSR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crypto.CertSigningRequestParams
		if args[1] != nil {
			arg1 = args[1].(crypto.CertSigningRequestParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Engine_CreateED25519CSR_Call) Return(privateKey ed25519.PrivateKey, bytes []byte, err error) *Engine_CreateED25519CSR_Call {
	_c.Call.Return(privateKey, bytes, err)
	return _c
}

func (_c *Engine_CreateED25519CSR_Call) RunAndReturn(run func(ctxt context.Context, csrParams crypto.CertSigningRequestParams) (ed25519.PrivateKey, []byte, error)) *Engine_CreateED25519CSR_Call {
	_c.Call.Return(run)
	return _c
}

// CreateED25519SelfSignedCA provides a mock function for the type Engine
func (_mock *Engine) CreateED25519SelfSignedCA(ctxt context.Context, caParams crypto.CertParams) (ed25519.PrivateKey, []byte, error) {
	ret := _mock.Called(ctxt, caParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateED25519SelfSignedCA")
	}

	var r0 ed25519.PrivateKey
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.CertParams) (ed25519.PrivateKey, []byte, error)); ok {
		return returnFunc(ctxt, caParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.CertParams) ed25519.PrivateKey); ok {
		r0 = returnFunc(ctxt, caParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ed25519.PrivateKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crypto.CertParams) []byte); ok {
		r1 = returnFunc(ctxt, caParams)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, crypto.CertParams) error); ok {
		r2 = returnFunc(ctxt, caParams)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Engine_CreateED25519SelfSignedCA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateED25519SelfSignedCA'
type Engine_CreateED25519SelfSignedCA_Call struct {
	*mock.Call
}

// CreateED25519SelfSignedCA is a helper method to define mock.On call
//   - ctxt context.Context
//   - caParams crypto.CertParams
func (_e *Engine_Expecter) CreateED25519SelfSignedCA(ctxt interface{}, caParams interface{}) *Engine_CreateED25519SelfSignedCA_Call {
	return &Engine_CreateED25519SelfSignedCA_Call{Call: _e.mock.On("CreateED25519SelfSignedCA", ctxt, caParams)}
}

func (_c *Engine_CreateED25519SelfSignedCA_Call) Run(run func(ctxt context.Context, caParams crypto.CertParams)) *Engine_CreateED25519SelfSignedCA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crypto.CertParams
		if args[1] != nil {
			arg1 = args[1].(crypto.CertParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Engine_CreateED25519SelfSignedCA_Call) Return(privateKey ed25519.PrivateKey, bytes []byte, err error) *Engine_CreateED25519SelfSignedCA_Call {
	_c.Call.Return(privateKey, bytes, err)
	return _c
}

func (_c *Engine_CreateED25519SelfSignedCA_Call) RunAndReturn(run func(ctxt context.Context, caParams crypto.CertParams) (ed25519.PrivateKey, []byte, error)) *Engine_CreateED25519SelfSignedCA_Call {
	_c.Call.Return(run)
	return _c
}

// GetAEAD provides a mock function for the type Engine
func (_mock *Engine) GetAEAD(ctxt context.Context, aeadType crypto.AEADTypeEnum) (crypto.AEAD, error) {
	ret := _mock.Called(ctxt, aeadType)

	if len(ret) == 0 {
		panic("no return value specified for GetAEAD")
	}

	var r0 crypto.AEAD
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.AEADTypeEnum) (crypto.AEAD, error)); ok {
		return returnFunc(ctxt, aeadType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.AEADTypeEnum) crypto.AEAD); ok {
		r0 = returnFunc(ctxt, aeadType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.AEAD)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crypto.AEADTypeEnum) error); ok {
		r1 = returnFunc(ctxt, aeadType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_GetAEAD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAEAD'
type Engine_GetAEAD_Call struct {
	*mock.Call
}

// GetAEAD is a helper method to define mock.On call
//   - ctxt context.Context
//   - aeadType crypto.AEADTypeEnum
func (_e *Engine_Expecter) GetAEAD(ctxt interface{}, aeadType interface{}) *Engine_GetAEAD_Call {
	return &Engine_GetAEAD_Call{Call: _e.mock.On("GetAEAD", ctxt, aeadType)}
}

func (_c *Engine_GetAEAD_Call) Run(run func(ctxt context.Context, aeadType crypto.AEADTypeEnum)) *Engine_GetAEAD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crypto.AEADTypeEnum
		if args[1] != nil {
			arg1 = args[1].(crypto.AEADTypeEnum)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Engine_GetAEAD_Call) Return(aEAD crypto.AEAD, err error) *Engine_GetAEAD_Call {
	_c.Call.Return(aEAD, err)
	return _c
}

func (_c *Engine_GetAEAD_Call) RunAndReturn(run func(ctxt context.Context, aeadType crypto.AEADTypeEnum) (crypto.AEAD, error)) *Engine_GetAEAD_Call {
	_c.Call.Return(run)
	return _c
}

// GetHasher provides a mock function for the type Engine
func (_mock *Engine) GetHasher(ctxt context.Context, key crypto.SecureCSlice) (crypto.Hasher, error) {
	ret := _mock.Called(ctxt, key)

	if len(ret) == 0 {
		panic("no return value specified for GetHasher")
	}

	var r0 crypto.Hasher
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.SecureCSlice) (crypto.Hasher, error)); ok {
		return returnFunc(ctxt, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.SecureCSlice) crypto.Hasher); ok {
		r0 = returnFunc(ctxt, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.Hasher)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crypto.SecureCSlice) error); ok {
		r1 = returnFunc(ctxt, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_GetHasher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHasher'
type Engine_GetHasher_Call struct {
	*mock.Call
}

// GetHasher is a helper method to define mock.On call
//   - ctxt context.Context
//   - key crypto.SecureCSlice
func (_e *Engine_Expecter) GetHasher(ctxt interface{}, key interface{}) *Engine_GetHasher_Call {
	return &Engine_GetHasher_Call{Call: _e.mock.On("GetHasher", ctxt, key)}
}

func (_c *Engine_GetHasher_Call) Run(run func(ctxt context.Context, key crypto.SecureCSlice)) *Engine_GetHasher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crypto.SecureCSlice
		if args[1] != nil {
			arg1 = args[1].(crypto.SecureCSlice)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Engine_GetHasher_Call) Return(hasher crypto.Hasher, err error) *Engine_GetHasher_Call {
	_c.Call.Return(hasher, err)
	return _c
}

func (_c *Engine_GetHasher_Call) RunAndReturn(run func(ctxt context.Context, key crypto.SecureCSlice) (crypto.Hasher, error)) *Engine_GetHasher_Call {
	_c.Call.Return(run)
	return _c
}

// GetHasherKey provides a mock function for the type Engine
func (_mock *Engine) GetHasherKey(ctxt context.Context) (crypto.SecureCSlice, error) {
	ret := _mock.Called(ctxt)

	if len(ret) == 0 {
		panic("no return value specified for GetHasherKey")
	}

	var r0 crypto.SecureCSlice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (crypto.SecureCSlice, error)); ok {
		return returnFunc(ctxt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) crypto.SecureCSlice); ok {
		r0 = returnFunc(ctxt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.SecureCSlice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctxt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_GetHasherKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHasherKey'
type Engine_GetHasherKey_Call struct {
	*mock.Call
}

// GetHasherKey is a helper method to define mock.On call
//   - ctxt context.Context
func (_e *Engine_Expecter) GetHasherKey(ctxt interface{}) *Engine_GetHasherKey_Call {
	return &Engine_GetHasherKey_Call{Call: _e.mock.On("GetHasherKey", ctxt)}
}

func (_c *Engine_GetHasherKey_Call) Run(run func(ctxt context.Context)) *Engine_GetHasherKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Engine_GetHasherKey_Call) Return(secureCSlice crypto.SecureCSlice, err error) *Engine_GetHasherKey_Call {
	_c.Call.Return(secureCSlice, err)
	return _c
}

func (_c *Engine_GetHasherKey_Call) RunAndReturn(run func(ctxt context.Context) (crypto.SecureCSlice, error)) *Engine_GetHasherKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetPBKDFSalt provides a mock function for the type Engine
func (_mock *Engine) GetPBKDFSalt(ctxt context.Context) (crypto.SecureCSlice, error) {
	ret := _mock.Called(ctxt)

	if len(ret) == 0 {
		panic("no return value specified for GetPBKDFSalt")
	}

	var r0 crypto.SecureCSlice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (crypto.SecureCSlice, error)); ok {
		return returnFunc(ctxt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) crypto.SecureCSlice); ok {
		r0 = returnFunc(ctxt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.SecureCSlice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctxt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_GetPBKDFSalt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPBKDFSalt'
type Engine_GetPBKDFSalt_Call struct {
	*mock.Call
}

// GetPBKDFSalt is a helper method to define mock.On call
//   - ctxt context.Context
func (_e *Engine_Expecter) GetPBKDFSalt(ctxt interface{}) *Engine_GetPBKDFSalt_Call {
	return &Engine_GetPBKDFSalt_Call{Call: _e.mock.On("GetPBKDFSalt", ctxt)}
}

func (_c *Engine_GetPBKDFSalt_Call) Run(run func(ctxt context.Context)) *Engine_GetPBKDFSalt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Engine_GetPBKDFSalt_Call) Return(secureCSlice crypto.SecureCSlice, err error) *Engine_GetPBKDFSalt_Call {
	_c.Call.Return(secureCSlice, err)
	return _c
}

func (_c *Engine_GetPBKDFSalt_Call) RunAndReturn(run func(ctxt context.Context) (crypto.SecureCSlice, error)) *Engine_GetPBKDFSalt_Call {
	_c.Call.Return(run)
	return _c
}

// GetRNGReader provides a mock function for the type Engine
func (_mock *Engine) GetRNGReader() io.Reader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRNGReader")
	}

	var r0 io.Reader
	if returnFunc, ok := ret.Get(0).(func() io.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	return r0
}

// Engine_GetRNGReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRNGReader'
type Engine_GetRNGReader_Call struct {
	*mock.Call
}

// GetRNGReader is a helper method to define mock.On call
func (_e *Engine_Expecter) GetRNGReader() *Engine_GetRNGReader_Call {
	return &Engine_GetRNGReader_Call{Call: _e.mock.On("GetRNGReader")}
}

func (_c *Engine_GetRNGReader_Call) Run(run func()) *Engine_GetRNGReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Engine_GetRNGReader_Call) Return(reader io.Reader) *Engine_GetRNGReader_Call {
	_c.Call.Return(reader)
	return _c
}

func (_c *Engine_GetRNGReader_Call) RunAndReturn(run func() io.Reader) *Engine_GetRNGReader_Call {
	_c.Call.Return(run)
	return _c
}

// GetRandomBuf provides a mock function for the type Engine
func (_mock *Engine) GetRandomBuf(ctxt context.Context, length int) (crypto.SecureCSlice, error) {
	ret := _mock.Called(ctxt, length)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomBuf")
	}

	var r0 crypto.SecureCSlice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (crypto.SecureCSlice, error)); ok {
		return returnFunc(ctxt, length)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) crypto.SecureCSlice); ok {
		r0 = returnFunc(ctxt, length)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.SecureCSlice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctxt, length)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_GetRandomBuf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomBuf'
type Engine_GetRandomBuf_Call struct {
	*mock.Call
}

// GetRandomBuf is a helper method to define mock.On call
//   - ctxt context.Context
//   - length int
func (_e *Engine_Expecter) GetRandomBuf(ctxt interface{}, length interface{}) *Engine_GetRandomBuf_Call {
	return &Engine_GetRandomBuf_Call{Call: _e.mock.On("GetRandomBuf", ctxt, length)}
}

func (_c *Engine_GetRandomBuf_Call) Run(run func(ctxt context.Context, length int)) *Engine_GetRandomBuf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Engine_GetRandomBuf_Call) Return(secureCSlice crypto.SecureCSlice, err error) *Engine_GetRandomBuf_Call {
	_c.Call.Return(secureCSlice, err)
	return _c
}

func (_c *Engine_GetRandomBuf_Call) RunAndReturn(run func(ctxt context.Context, length int) (crypto.SecureCSlice, error)) *Engine_GetRandomBuf_Call {
	_c.Call.Return(run)
	return _c
}

// NewECDHKeyPair provides a mock function for the type Engine
func (_mock *Engine) NewECDHKeyPair(ctxt context.Context) (crypto.ECDHKeyPair, error) {
	ret := _mock.Called(ctxt)

	if len(ret) == 0 {
		panic("no return value specified for NewECDHKeyPair")
	}

	var r0 crypto.ECDHKeyPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (crypto.ECDHKeyPair, error)); ok {
		return returnFunc(ctxt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) crypto.ECDHKeyPair); ok {
		r0 = returnFunc(ctxt)
	} else {
		r0 = ret.Get(0).(crypto.ECDHKeyPair)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctxt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_NewECDHKeyPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewECDHKeyPair'
type Engine_NewECDHKeyPair_Call struct {
	*mock.Call
}

// NewECDHKeyPair is a helper method to define mock.On call
//   - ctxt context.Context
func (_e *Engine_Expecter) NewECDHKeyPair(ctxt interface{}) *Engine_NewECDHKeyPair_Call {
	return &Engine_NewECDHKeyPair_Call{Call: _e.mock.On("NewECDHKeyPair", ctxt)}
}

func (_c *Engine_NewECDHKeyPair_Call) Run(run func(ctxt context.Context)) *Engine_NewECDHKeyPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Engine_NewECDHKeyPair_Call) Return(eCDHKeyPair crypto.ECDHKeyPair, err error) *Engine_NewECDHKeyPair_Call {
	_c.Call.Return(eCDHKeyPair, err)
	return _c
}

func (_c *Engine_NewECDHKeyPair_Call) RunAndReturn(run func(ctxt context.Context) (crypto.ECDHKeyPair, error)) *Engine_NewECDHKeyPair_Call {
	_c.Call.Return(run)
	return _c
}

// PBKDF provides a mock function for the type Engine
func (_mock *Engine) PBKDF(ctxt context.Context, passwd []byte, salt crypto.SecureCSlice, opsLimit uint64, memLimit uint64, outLength int) (crypto.SecureCSlice, error) {
	ret := _mock.Called(ctxt, passwd, salt, opsLimit, memLimit, outLength)

	if len(ret) == 0 {
		panic("no return value specified for PBKDF")
	}

	var r0 crypto.SecureCSlice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, crypto.SecureCSlice, uint64, uint64, int) (crypto.SecureCSlice, error)); ok {
		return returnFunc(ctxt, passwd, salt, opsLimit, memLimit, outLength)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, crypto.SecureCSlice, uint64, uint64, int) crypto.SecureCSlice); ok {
		r0 = returnFunc(ctxt, passwd, salt, opsLimit, memLimit, outLength)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.SecureCSlice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, crypto.SecureCSlice, uint64, uint64, int) error); ok {
		r1 = returnFunc(ctxt, passwd, salt, opsLimit, memLimit, outLength)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_PBKDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PBKDF'
type Engine_PBKDF_Call struct {
	*mock.Call
}

// PBKDF is a helper method to define mock.On call
//   - ctxt context.Context
//   - passwd []byte
//   - salt crypto.SecureCSlice
//   - opsLimit uint64
//   - memLimit uint64
//   - outLength int
func (_e *Engine_Expecter) PBKDF(ctxt interface{}, passwd interface{}, salt interface{}, opsLimit interface{}, memLimit interface{}, outLength interface{}) *Engine_PBKDF_Call {
	return &Engine_PBKDF_Call{Call: _e.mock.On("PBKDF", ctxt, passwd, salt, opsLimit, memLimit, outLength)}
}

func (_c *Engine_PBKDF_Call) Run(run func(ctxt context.Context, passwd []byte, salt crypto.SecureCSlice, opsLimit uint64, memLimit uint64, outLength int)) *Engine_PBKDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 crypto.SecureCSlice
		if args[2] != nil {
			arg2 = args[2].(crypto.SecureCSlice)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *Engine_PBKDF_Call) Return(secureCSlice crypto.SecureCSlice, err error) *Engine_PBKDF_Call {
	_c.Call.Return(secureCSlice, err)
	return _c
}

func (_c *Engine_PBKDF_Call) RunAndReturn(run func(ctxt context.Context, passwd []byte, salt crypto.SecureCSlice, opsLimit uint64, memLimit uint64, outLength int) (crypto.SecureCSlice, error)) *Engine_PBKDF_Call {
	_c.Call.Return(run)
	return _c
}

// ParseCertificateFromPEM provides a mock function for the type Engine
func (_mock *Engine) ParseCertificateFromPEM(ctxt context.Context, certPem string) (*x509.Certificate, error) {
	ret := _mock.Called(ctxt, certPem)

	if len(ret) == 0 {
		panic("no return value specified for ParseCertificateFromPEM")
	}

	var r0 *x509.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*x509.Certificate, error)); ok {
		return returnFunc(ctxt, certPem)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *x509.Certificate); ok {
		r0 = returnFunc(ctxt, certPem)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*x509.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctxt, certPem)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_ParseCertificateFromPEM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseCertificateFromPEM'
type Engine_ParseCertificateFromPEM_Call struct {
	*mock.Call
}

// ParseCertificateFromPEM is a helper method to define mock.On call
//   - ctxt context.Context
//   - certPem string
func (_e *Engine_Expecter) ParseCertificateFromPEM(ctxt interface{}, certPem interface{}) *Engine_ParseCertificateFromPEM_Call {
	return &Engine_ParseCertificateFromPEM_Call{Call: _e.mock.On("ParseCertificateFromPEM", ctxt, certPem)}
}

func (_c *Engine_ParseCertificateFromPEM_Call) Run(run func(ctxt context.Context, certPem string)) *Engine_ParseCertificateFromPEM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Engine_ParseCertificateFromPEM_Call) Return(certificate *x509.Certificate, err error) *Engine_ParseCertificateFromPEM_Call {
	_c.Call.Return(certificate, err)
	return _c
}

func (_c *Engine_ParseCertificateFromPEM_Call) RunAndReturn(run func(ctxt context.Context, certPem string) (*x509.Certificate, error)) *Engine_ParseCertificateFromPEM_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRSAPrivateKeyFromPEM provides a mock function for the type Engine
func (_mock *Engine) ParseRSAPrivateKeyFromPEM(ctxt context.Context, keyPem string) (*rsa.PrivateKey, error) {
	ret := _mock.Called(ctxt, keyPem)

	if len(ret) == 0 {
		panic("no return value specified for ParseRSAPrivateKeyFromPEM")
	}

	var r0 *rsa.PrivateKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*rsa.PrivateKey, error)); ok {
		return returnFunc(ctxt, keyPem)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *rsa.PrivateKey); ok {
		r0 = returnFunc(ctxt, keyPem)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PrivateKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctxt, keyPem)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_ParseRSAPrivateKeyFromPEM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRSAPrivateKeyFromPEM'
type Engine_ParseRSAPrivateKeyFromPEM_Call struct {
	*mock.Call
}

// ParseRSAPrivateKeyFromPEM is a helper method to define mock.On call
//   - ctxt context.Context
//   - keyPem string
func (_e *Engine_Expecter) ParseRSAPrivateKeyFromPEM(ctxt interface{}, keyPem interface{}) *Engine_ParseRSAPrivateKeyFromPEM_Call {
	return &Engine_ParseRSAPrivateKeyFromPEM_Call{Call: _e.mock.On("ParseRSAPrivateKeyFromPEM", ctxt, keyPem)}
}

func (_c *Engine_ParseRSAPrivateKeyFromPEM_Call) Run(run func(ctxt context.Context, keyPem string)) *Engine_ParseRSAPrivateKeyFromPEM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Engine_ParseRSAPrivateKeyFromPEM_Call) Return(privateKey *rsa.PrivateKey, err error) *Engine_ParseRSAPrivateKeyFromPEM_Call {
	_c.Call.Return(privateKey, err)
	return _c
}

func (_c *Engine_ParseRSAPrivateKeyFromPEM_Call) RunAndReturn(run func(ctxt context.Context, keyPem string) (*rsa.PrivateKey, error)) *Engine_ParseRSAPrivateKeyFromPEM_Call {
	_c.Call.Return(run)
	return _c
}

// RSADecrypt provides a mock function for the type Engine
func (_mock *Engine) RSADecrypt(ctxt context.Context, cipherText []byte, privKey *rsa.PrivateKey, dataLabel []byte) ([]byte, error) {
	ret := _mock.Called(ctxt, cipherText, privKey, dataLabel)

	if len(ret) == 0 {
		panic("no return value specified for RSADecrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, *rsa.PrivateKey, []byte) ([]byte, error)); ok {
		return returnFunc(ctxt, cipherText, privKey, dataLabel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, *rsa.PrivateKey, []byte) []byte); ok {
		r0 = returnFunc(ctxt, cipherText, privKey, dataLabel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, *rsa.PrivateKey, []byte) error); ok {
		r1 = returnFunc(ctxt, cipherText, privKey, dataLabel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_RSADecrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RSADecrypt'
type Engine_RSADecrypt_Call struct {
	*mock.Call
}

// RSADecrypt is a helper method to define mock.On call
//   - ctxt context.Context
//   - cipherText []byte
//   - privKey *rsa.PrivateKey
//   - dataLabel []byte
func (_e *Engine_Expecter) RSADecrypt(ctxt interface{}, cipherText interface{}, privKey interface{}, dataLabel interface{}) *Engine_RSADecrypt_Call {
	return &Engine_RSADecrypt_Call{Call: _e.mock.On("RSADecrypt", ctxt, cipherText, privKey, dataLabel)}
}

func (_c *Engine_RSADecrypt_Call) Run(run func(ctxt context.Context, cipherText []byte, privKey *rsa.PrivateKey, dataLabel []byte)) *Engine_RSADecrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 *rsa.PrivateKey
		if args[2] != nil {
			arg2 = args[2].(*rsa.PrivateKey)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Engine_RSADecrypt_Call) Return(bytes []byte, err error) *Engine_RSADecrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Engine_RSADecrypt_Call) RunAndReturn(run func(ctxt context.Context, cipherText []byte, privKey *rsa.PrivateKey, dataLabel []byte) ([]byte, error)) *Engine_RSADecrypt_Call {
	_c.Call.Return(run)
	return _c
}

// RSAEncrypt provides a mock function for the type Engine
func (_mock *Engine) RSAEncrypt(ctxt context.Context, plainText []byte, pubKey *rsa.PublicKey, dataLabel []byte) ([]byte, error) {
	ret := _mock.Called(ctxt, plainText, pubKey, dataLabel)

	if len(ret) == 0 {
		panic("no return value specified for RSAEncrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, *rsa.PublicKey, []byte) ([]byte, error)); ok {
		return returnFunc(ctxt, plainText, pubKey, dataLabel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, *rsa.PublicKey, []byte) []byte); ok {
		r0 = returnFunc(ctxt, plainText, pubKey, dataLabel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, *rsa.PublicKey, []byte) error); ok {
		r1 = returnFunc(ctxt, plainText, pubKey, dataLabel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_RSAEncrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RSAEncrypt'
type Engine_RSAEncrypt_Call struct {
	*mock.Call
}

// RSAEncrypt is a helper method to define mock.On call
//   - ctxt context.Context
//   - plainText []byte
//   - pubKey *rsa.PublicKey
//   - dataLabel []byte
func (_e *Engine_Expecter) RSAEncrypt(ctxt interface{}, plainText interface{}, pubKey interface{}, dataLabel interface{}) *Engine_RSAEncrypt_Call {
	return &Engine_RSAEncrypt_Call{Call: _e.mock.On("RSAEncrypt", ctxt, plainText, pubKey, dataLabel)}
}

func (_c *Engine_RSAEncrypt_Call) Run(run func(ctxt context.Context, plainText []byte, pubKey *rsa.PublicKey, dataLabel []byte)) *Engine_RSAEncrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 *rsa.PublicKey
		if args[2] != nil {
			arg2 = args[2].(*rsa.PublicKey)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Engine_RSAEncrypt_Call) Return(bytes []byte, err error) *Engine_RSAEncrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Engine_RSAEncrypt_Call) RunAndReturn(run func(ctxt context.Context, plainText []byte, pubKey *rsa.PublicKey, dataLabel []byte) ([]byte, error)) *Engine_RSAEncrypt_Call {
	_c.Call.Return(run)
	return _c
}

// ReadED25519PublicKeyFromCert provides a mock function for the type Engine
func (_mock *Engine) ReadED25519PublicKeyFromCert(ctxt context.Context, cert *x509.Certificate) (ed25519.PublicKey, error) {
	ret := _mock.Called(ctxt, cert)

	if len(ret) == 0 {
		panic("no return value specified for ReadED25519PublicKeyFromCert")
	}

	var r0 ed25519.PublicKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *x509.Certificate) (ed25519.PublicKey, error)); ok {
		return returnFunc(ctxt, cert)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *x509.Certificate) ed25519.PublicKey); ok {
		r0 = returnFunc(ctxt, cert)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ed25519.PublicKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *x509.Certificate) error); ok {
		r1 = returnFunc(ctxt, cert)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_ReadED25519PublicKeyFromCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadED25519PublicKeyFromCert'
type Engine_ReadED25519PublicKeyFromCert_Call struct {
	*mock.Call
}

// ReadED25519PublicKeyFromCert is a helper method to define mock.On call
//   - ctxt context.Context
//   - cert *x509.Certificate
func (_e *Engine_Expecter) ReadED25519PublicKeyFromCert(ctxt interface{}, cert interface{}) *Engine_ReadED25519PublicKeyFromCert_Call {
	return &Engine_ReadED25519PublicKeyFromCert_Call{Call: _e.mock.On("ReadED25519PublicKeyFromCert", ctxt, cert)}
}

func (_c *Engine_ReadED25519PublicKeyFromCert_Call) Run(run func(ctxt context.Context, cert *x509.Certificate)) *Engine_ReadED25519PublicKeyFromCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *x509.Certificate
		if args[1] != nil {
			arg1 = args[1].(*x509.Certificate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Engine_ReadED25519PublicKeyFromCert_Call) Return(publicKey ed25519.PublicKey, err error) *Engine_ReadED25519PublicKeyFromCert_Call {
	_c.Call.Return(publicKey, err)
	return _c
}

func (_c *Engine_ReadED25519PublicKeyFromCert_Call) RunAndReturn(run func(ctxt context.Context, cert *x509.Certificate) (ed25519.PublicKey, error)) *Engine_ReadED25519PublicKeyFromCert_Call {
	_c.Call.Return(run)
	return _c
}

// ReadRSAPublicKeyFromCert provides a mock function for the type Engine
func (_mock *Engine) ReadRSAPublicKeyFromCert(ctxt context.Context, cert *x509.Certificate) (*rsa.PublicKey, error) {
	ret := _mock.Called(ctxt, cert)

	if len(ret) == 0 {
		panic("no return value specified for ReadRSAPublicKeyFromCert")
	}

	var r0 *rsa.PublicKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *x509.Certificate) (*rsa.PublicKey, error)); ok {
		return returnFunc(ctxt, cert)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *x509.Certificate) *rsa.PublicKey); ok {
		r0 = returnFunc(ctxt, cert)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PublicKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *x509.Certificate) error); ok {
		r1 = returnFunc(ctxt, cert)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Engine_ReadRSAPublicKeyFromCert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadRSAPublicKeyFromCert'
type Engine_ReadRSAPublicKeyFromCert_Call struct {
	*mock.Call
}

// ReadRSAPublicKeyFromCert is a helper method to define mock.On call
//   - ctxt context.Context
//   - cert *x509.Certificate
func (_e *Engine_Expecter) ReadRSAPublicKeyFromCert(ctxt interface{}, cert interface{}) *Engine_ReadRSAPublicKeyFromCert_Call {
	return &Engine_ReadRSAPublicKeyFromCert_Call{Call: _e.mock.On("ReadRSAPublicKeyFromCert", ctxt, cert)}
}

func (_c *Engine_ReadRSAPublicKeyFromCert_Call) Run(run func(ctxt context.Context, cert *x509.Certificate)) *Engine_ReadRSAPublicKeyFromCert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *x509.Certificate
		if args[1] != nil {
			arg1 = args[1].(*x509.Certificate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Engine_ReadRSAPublicKeyFromCert_Call) Return(publicKey *rsa.PublicKey, err error) *Engine_ReadRSAPublicKeyFromCert_Call {
	_c.Call.Return(publicKey, err)
	return _c
}

func (_c *Engine_ReadRSAPublicKeyFromCert_Call) RunAndReturn(run func(ctxt context.Context, cert *x509.Certificate) (*rsa.PublicKey, error)) *Engine_ReadRSAPublicKeyFromCert_Call {
	_c.Call.Return(run)
	return _c
}
