// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcrypto

import (
	mock "github.com/stretchr/testify/mock"
)

// NewHasher creates a new instance of Hasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hasher {
	mock := &Hasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Hasher is an autogenerated mock type for the Hasher type
type Hasher struct {
	mock.Mock
}

type Hasher_Expecter struct {
	mock *mock.Mock
}

func (_m *Hasher) EXPECT() *Hasher_Expecter {
	return &Hasher_Expecter{mock: &_m.Mock}
}

// Finalize provides a mock function for the type Hasher
func (_mock *Hasher) Finalize() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Finalize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Hasher_Finalize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finalize'
type Hasher_Finalize_Call struct {
	*mock.Call
}

// Finalize is a helper method to define mock.On call
func (_e *Hasher_Expecter) Finalize() *Hasher_Finalize_Call {
	return &Hasher_Finalize_Call{Call: _e.mock.On("Finalize")}
}

func (_c *Hasher_Finalize_Call) Run(run func()) *Hasher_Finalize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Hasher_Finalize_Call) Return(err error) *Hasher_Finalize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Hasher_Finalize_Call) RunAndReturn(run func() error) *Hasher_Finalize_Call {
	_c.Call.Return(run)
	return _c
}

// GetHash provides a mock function for the type Hasher
func (_mock *Hasher) GetHash() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHash")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// Hasher_GetHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHash'
type Hasher_GetHash_Call struct {
	*mock.Call
}

// GetHash is a helper method to define mock.On call
func (_e *Hasher_Expecter) GetHash() *Hasher_GetHash_Call {
	return &Hasher_GetHash_Call{Call: _e.mock.On("GetHash")}
}

func (_c *Hasher_GetHash_Call) Run(run func()) *Hasher_GetHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Hasher_GetHash_Call) Return(bytes []byte) *Hasher_GetHash_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *Hasher_GetHash_Call) RunAndReturn(run func() []byte) *Hasher_GetHash_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Hasher
func (_mock *Hasher) Update(buf []byte) error {
	ret := _mock.Called(buf)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(buf)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Hasher_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Hasher_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - buf []byte
func (_e *Hasher_Expecter) Update(buf interface{}) *Hasher_Update_Call {
	return &Hasher_Update_Call{Call: _e.mock.On("Update", buf)}
}

func (_c *Hasher_Update_Call) Run(run func(buf []byte)) *Hasher_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Hasher_Update_Call) Return(err error) *Hasher_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Hasher_Update_Call) RunAndReturn(run func(buf []byte) error) *Hasher_Update_Call {
	_c.Call.Return(run)
	return _c
}
