// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcrypto

import (
	"math/big"
	"unsafe"

	mock "github.com/stretchr/testify/mock"
)

// NewSecureCSlice creates a new instance of SecureCSlice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecureCSlice(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecureCSlice {
	mock := &SecureCSlice{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SecureCSlice is an autogenerated mock type for the SecureCSlice type
type SecureCSlice struct {
	mock.Mock
}

type SecureCSlice_Expecter struct {
	mock *mock.Mock
}

func (_m *SecureCSlice) EXPECT() *SecureCSlice_Expecter {
	return &SecureCSlice_Expecter{mock: &_m.Mock}
}

// AddValue provides a mock function for the type SecureCSlice
func (_mock *SecureCSlice) AddValue(value *big.Int) error {
	ret := _mock.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for AddValue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*big.Int) error); ok {
		r0 = returnFunc(value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SecureCSlice_AddValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddValue'
type SecureCSlice_AddValue_Call struct {
	*mock.Call
}

// AddValue is a helper method to define mock.On call
//   - value *big.Int
func (_e *SecureCSlice_Expecter) AddValue(value interface{}) *SecureCSlice_AddValue_Call {
	return &SecureCSlice_AddValue_Call{Call: _e.mock.On("AddValue", value)}
}

func (_c *SecureCSlice_AddValue_Call) Run(run func(value *big.Int)) *SecureCSlice_AddValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *big.Int
		if args[0] != nil {
			arg0 = args[0].(*big.Int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SecureCSlice_AddValue_Call) Return(err error) *SecureCSlice_AddValue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SecureCSlice_AddValue_Call) RunAndReturn(run func(value *big.Int) error) *SecureCSlice_AddValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetCArray provides a mock function for the type SecureCSlice
func (_mock *SecureCSlice) GetCArray() (unsafe.Pointer, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCArray")
	}

	var r0 unsafe.Pointer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (unsafe.Pointer, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecureCSlice_GetCArray_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCArray'
type SecureCSlice_GetCArray_Call struct {
	*mock.Call
}

// GetCArray is a helper method to define mock.On call
func (_e *SecureCSlice_Expecter) GetCArray() *SecureCSlice_GetCArray_Call {
	return &SecureCSlice_GetCArray_Call{Call: _e.mock.On("GetCArray")}
}

func (_c *SecureCSlice_GetCArray_Call) Run(run func()) *SecureCSlice_GetCArray_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SecureCSlice_GetCArray_Call) Return(v unsafe.Pointer, err error) *SecureCSlice_GetCArray_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *SecureCSlice_GetCArray_Call) RunAndReturn(run func() (unsafe.Pointer, error)) *SecureCSlice_GetCArray_Call {
	_c.Call.Return(run)
	return _c
}

// GetLen provides a mock function for the type SecureCSlice
func (_mock *SecureCSlice) GetLen() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLen")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecureCSlice_GetLen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLen'
type SecureCSlice_GetLen_Call struct {
	*mock.Call
}

// GetLen is a helper method to define mock.On call
func (_e *SecureCSlice_Expecter) GetLen() *SecureCSlice_GetLen_Call {
	return &SecureCSlice_GetLen_Call{Call: _e.mock.On("GetLen")}
}

func (_c *SecureCSlice_GetLen_Call) Run(run func()) *SecureCSlice_GetLen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SecureCSlice_GetLen_Call) Return(n int, err error) *SecureCSlice_GetLen_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *SecureCSlice_GetLen_Call) RunAndReturn(run func() (int, error)) *SecureCSlice_GetLen_Call {
	_c.Call.Return(run)
	return _c
}

// GetSlice provides a mock function for the type SecureCSlice
func (_mock *SecureCSlice) GetSlice() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSlice")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecureCSlice_GetSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlice'
type SecureCSlice_GetSlice_Call struct {
	*mock.Call
}

// GetSlice is a helper method to define mock.On call
func (_e *SecureCSlice_Expecter) GetSlice() *SecureCSlice_GetSlice_Call {
	return &SecureCSlice_GetSlice_Call{Call: _e.mock.On("GetSlice")}
}

func (_c *SecureCSlice_GetSlice_Call) Run(run func()) *SecureCSlice_GetSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SecureCSlice_GetSlice_Call) Return(bytes []byte, err error) *SecureCSlice_GetSlice_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *SecureCSlice_GetSlice_Call) RunAndReturn(run func() ([]byte, error)) *SecureCSlice_GetSlice_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementValue provides a mock function for the type SecureCSlice
func (_mock *SecureCSlice) IncrementValue() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IncrementValue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SecureCSlice_IncrementValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementValue'
type SecureCSlice_IncrementValue_Call struct {
	*mock.Call
}

// IncrementValue is a helper method to define mock.On call
func (_e *SecureCSlice_Expecter) IncrementValue() *SecureCSlice_IncrementValue_Call {
	return &SecureCSlice_IncrementValue_Call{Call: _e.mock.On("IncrementValue")}
}

func (_c *SecureCSlice_IncrementValue_Call) Run(run func()) *SecureCSlice_IncrementValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SecureCSlice_IncrementValue_Call) Return(err error) *SecureCSlice_IncrementValue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SecureCSlice_IncrementValue_Call) RunAndReturn(run func() error) *SecureCSlice_IncrementValue_Call {
	_c.Call.Return(run)
	return _c
}

// Zero provides a mock function for the type SecureCSlice
func (_mock *SecureCSlice) Zero() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Zero")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SecureCSlice_Zero_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Zero'
type SecureCSlice_Zero_Call struct {
	*mock.Call
}

// Zero is a helper method to define mock.On call
func (_e *SecureCSlice_Expecter) Zero() *SecureCSlice_Zero_Call {
	return &SecureCSlice_Zero_Call{Call: _e.mock.On("Zero")}
}

func (_c *SecureCSlice_Zero_Call) Run(run func()) *SecureCSlice_Zero_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SecureCSlice_Zero_Call) Return(err error) *SecureCSlice_Zero_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SecureCSlice_Zero_Call) RunAndReturn(run func() error) *SecureCSlice_Zero_Call {
	_c.Call.Return(run)
	return _c
}
